#include "anagramlist.h"

struct anagram anagramlist[] = {
    { "admirer" },
    { "alarming" },
    { "anoint" },
    { "battle" },
    { "bookcase" },
    { "compliant" },
    { "conical" },
    { "considerate" },
    { "corona" },
    { "cruelty" },
    { "decoration" },
    { "despoil" },
    { "director" },
    { "earth" },
    { "fluster" },
    { "gardenia" },
    { "incognito" },
    { "lattice" },
    { "logarithm" },
    { "medicate" },
    { "meeting" },
    { "meteor" },
    { "mile" },
    { "mischance" },
    { "misshape" },
    { "mode" },
    { "nameless" },
    { "orchestra" },
    { "outside" },
    { "pastel" },
    { "prenatal" },
    { "presume" },
    { "reductions" },
    { "sectional" },
    { "sideboard" },
    { "spatula" },
    { "stainless" },
    { "strainer" },
    { "stream" },
    { "tentative" },
    { "thicken" },
    { "truffle" },
    { "unnoticed" },
    { "warehouse" },
};
int anagramlistsize = sizeof anagramlist / sizeof anagramlist[0];
